name: Generate Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: Platane/snk@v3
        with:
          github_user_name: iaanne
          outputs: |
            output/galaga-contribution-graph.svg?color_snake=#24f100&color_dots=#ebedf0,#9be9a8,#40c463,#30a14e,#216e39
            output/galaga-contribution-graph-dark.svg?color_snake=#24f100&color_dots=#161b22,#0e4429,#006d32,#26a641,#39d353
